// @ts-nocheck — kept as reference for the original mock data shape
import type { Customer, Task, Event } from '@/types';

// ─── Customers ───────────────────────────────────────────────────────

export const customers: Customer[] = [
  {
    id: 'rec_cust_sarah_001',
    customerName: 'Sarah Chen',
    type: 'D2C Standard',
    broker: 'Direct',
    currentStage: 'Review Your Designs',
    stageEnteredAt: '2026-04-18T14:00:00.000Z',
    contactEmail: 'sarah@chenhomes.com',
    platformEmail: 'sarah@chenhomes.com',
    phone: '(305) 555-0142',
    businessName: 'Chen Premier Realty',
    businessAddress: '1200 Brickell Ave, Suite 400, Miami, FL 33131',
    website: 'https://www.chenhomes.com',
    serviceAreas: 'Brickell, Coral Gables, Coconut Grove, Key Biscayne',
    bio: 'Sarah Chen is a top-producing agent specializing in luxury condos and waterfront properties in the Miami metro area. With over 12 years of experience, she has closed $200M+ in transactions and is known for her personalized approach to each client.',
    licenseNumber: 'SL3421987',
    topics: 'Luxury Real Estate, Miami Condos, Waterfront Living, Market Updates',
    hashtags: '#MiamiRealEstate #LuxuryLiving #ChenHomes #BrickellCondos',
    gmbName: 'Chen Premier Realty - Sarah Chen',
    mlsIds: '["MIAMIRE-12345"]',
    agentPhoto: ['https://storage.example.com/photos/sarah-chen-headshot.jpg'],
    businessLogo: ['https://storage.example.com/logos/chen-premier-realty.png'],
    otherAssets: ['https://storage.example.com/assets/chen-brand-guide.pdf'],
    specialInstructions: 'Prefers a modern minimalist aesthetic. Use navy blue and gold color palette. Include QR code on business cards.',
    hubspotDealId: 'HS-88234',
    stripePaymentId: 'pi_3PxQ2r4kLm8nRtUv',
    addOnStripePaymentId: '',
    productTier: 'Luxury',
    paymentStatus: 'Paid',
    csmAssigned: 'Mario',
    designApproval: 'Pending',
    designFeedback: '',
    accountCreated: false,
    credentialsSent: false,
    callBooked: false,
    callCompleted: false,
    accessToken: 'rec_cust_sarah_001',
    tasks: [],
    events: [],
    createdAt: '2026-04-10T09:30:00.000Z',
    lastModified: '2026-04-18T14:00:00.000Z',
  },
  {
    id: 'rec_cust_james_002',
    customerName: 'James Rodriguez',
    type: 'Keyes',
    broker: 'Keyes',
    currentStage: 'Getting Started',
    stageEnteredAt: '2026-04-21T10:00:00.000Z',
    contactEmail: 'james.rodriguez@keyesrealty.com',
    platformEmail: '',
    phone: '(954) 555-0287',
    businessName: 'The Keyes Company',
    businessAddress: '5300 N Federal Hwy, Fort Lauderdale, FL 33308',
    website: 'https://www.keyes.com/agents/james-rodriguez',
    serviceAreas: 'Fort Lauderdale, Plantation, Weston, Davie, Sunrise',
    bio: 'James Rodriguez is a bilingual real estate professional serving the Broward County market. Specializing in residential properties and first-time homebuyers, James brings 5 years of experience and a passion for helping families find their perfect home.',
    licenseNumber: 'SL3498712',
    topics: 'First-Time Buyers, Broward County Homes, Bilingual Agent, Market Insights',
    hashtags: '#KeyesAgent #BrowardHomes #FortLauderdaleRealtor #JamesRodriguezRealtor',
    gmbName: 'James Rodriguez - Keyes Real Estate',
    mlsIds: '["BWMLS-67890", "SFMLS-11223"]',
    agentPhoto: ['https://roster.keyes.com/photos/james-rodriguez.jpg'],
    businessLogo: ['https://roster.keyes.com/logos/keyes-company.png'],
    otherAssets: [],
    specialInstructions: '',
    hubspotDealId: '',
    stripePaymentId: '',
    addOnStripePaymentId: '',
    productTier: null,
    paymentStatus: null,
    csmAssigned: 'Luis',
    designApproval: null,
    designFeedback: '',
    accountCreated: false,
    credentialsSent: false,
    callBooked: false,
    callCompleted: false,
    accessToken: 'rec_cust_james_002',
    tasks: [],
    events: [],
    createdAt: '2026-04-21T10:00:00.000Z',
    lastModified: '2026-04-21T10:00:00.000Z',
  },
];

// ─── Tasks: Sarah Chen (D2C Standard — 16 tasks) ────────────────────

const sarahTasks: Task[] = [
  // Stage 1: Getting Started (3 tasks) — all Completed
  {
    id: 'rec_task_sc_001',
    taskName: 'Complete Your Onboarding Form',
    customer: ['rec_cust_sarah_001'],
    type: 'Client',
    stage: 'Getting Started',
    status: 'Completed',
    taskOrder: 1,
    assignedTo: null,
    visibleToClient: true,
    dependsOn: '',
    hasTeamReview: false,
    attachmentType: 'Form',
    embedUrl: '',
    instructions: 'Please complete this form so our team can get started on your brand kit.',
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '2026-04-12T11:30:00.000Z',
    createdAt: '2026-04-10T09:30:00.000Z',
  },
  {
    id: 'rec_task_sc_002',
    taskName: 'Upload Logos and Headshots',
    customer: ['rec_cust_sarah_001'],
    type: 'Client',
    stage: 'Getting Started',
    status: 'Completed',
    taskOrder: 2,
    assignedTo: null,
    visibleToClient: true,
    dependsOn: '',
    hasTeamReview: false,
    attachmentType: 'File Upload',
    embedUrl: '',
    instructions: 'Upload your logo files (PNG/SVG preferred), professional headshots, and any brand assets.',
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '2026-04-13T16:45:00.000Z',
    createdAt: '2026-04-10T09:30:00.000Z',
  },
  {
    id: 'rec_task_sc_003',
    taskName: 'Create Designs',
    customer: ['rec_cust_sarah_001'],
    type: 'Team',
    stage: 'Getting Started',
    status: 'Completed',
    taskOrder: 3,
    assignedTo: 'Designer',
    visibleToClient: false,
    dependsOn: 'Upload Logos and Headshots',
    hasTeamReview: true,
    attachmentType: 'None',
    embedUrl: '',
    instructions: 'Pull assets from client submissions. Create brand kit design using uploaded logos, headshots, and bio.',
    tags: [],
    notes: 'Used navy + gold palette per client instructions. SR approved v2.',
    dueDate: '',
    completedAt: '2026-04-17T10:00:00.000Z',
    createdAt: '2026-04-10T09:30:00.000Z',
  },

  // Stage 2: Review Your Designs (2 tasks) — Upload Proof Active, Review Draft
  {
    id: 'rec_task_sc_004',
    taskName: 'Upload Proof to Customer',
    customer: ['rec_cust_sarah_001'],
    type: 'Team',
    stage: 'Review Your Designs',
    status: 'Active',
    taskOrder: 1,
    assignedTo: 'Designer',
    visibleToClient: false,
    dependsOn: 'Create Designs',
    hasTeamReview: false,
    attachmentType: 'None',
    embedUrl: '',
    instructions: 'Upload the approved design files to the client review task.',
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-10T09:30:00.000Z',
  },
  {
    id: 'rec_task_sc_005',
    taskName: 'Review & Approve Your Brand Kit',
    customer: ['rec_cust_sarah_001'],
    type: 'Client',
    stage: 'Review Your Designs',
    status: 'Draft',
    taskOrder: 2,
    assignedTo: null,
    visibleToClient: true,
    dependsOn: 'Upload Proof to Customer',
    hasTeamReview: false,
    attachmentType: 'Proof',
    embedUrl: '',
    instructions: 'Please review your brand kit. If everything looks correct, click Approve. If changes are needed, click Request Changes and describe what needs updating.',
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-10T09:30:00.000Z',
  },

  // Stage 3: Book Your Call (4 tasks) — all Draft
  {
    id: 'rec_task_sc_006',
    taskName: 'Move Designs to Production',
    customer: ['rec_cust_sarah_001'],
    type: 'Team',
    stage: 'Book Your Call',
    status: 'Draft',
    taskOrder: 1,
    assignedTo: 'Designer',
    visibleToClient: false,
    dependsOn: '',
    hasTeamReview: false,
    attachmentType: 'None',
    embedUrl: '',
    instructions: 'Move approved design assets to the production environment.',
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-10T09:30:00.000Z',
  },
  {
    id: 'rec_task_sc_007',
    taskName: 'Create Customer Account',
    customer: ['rec_cust_sarah_001'],
    type: 'Team',
    stage: 'Book Your Call',
    status: 'Draft',
    taskOrder: 2,
    assignedTo: 'Onboarding Ops',
    visibleToClient: false,
    dependsOn: 'Move Designs to Production',
    hasTeamReview: false,
    attachmentType: 'None',
    embedUrl: '',
    instructions: "Create the customer's app.rejig.ai account using their Platform Email.",
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-10T09:30:00.000Z',
  },
  {
    id: 'rec_task_sc_008',
    taskName: 'Send Credentials',
    customer: ['rec_cust_sarah_001'],
    type: 'Team',
    stage: 'Book Your Call',
    status: 'Draft',
    taskOrder: 3,
    assignedTo: 'Onboarding Ops',
    visibleToClient: false,
    dependsOn: 'Create Customer Account',
    hasTeamReview: false,
    attachmentType: 'None',
    embedUrl: '',
    instructions: 'Send login credentials to the customer.',
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-10T09:30:00.000Z',
  },
  {
    id: 'rec_task_sc_009',
    taskName: 'Schedule Your Onboarding Call',
    customer: ['rec_cust_sarah_001'],
    type: 'Client',
    stage: 'Book Your Call',
    status: 'Draft',
    taskOrder: 4,
    assignedTo: null,
    visibleToClient: true,
    dependsOn: 'Send Credentials',
    hasTeamReview: false,
    attachmentType: 'Embed',
    embedUrl: '',
    instructions: 'Book your onboarding call at a time that works for you.',
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-10T09:30:00.000Z',
  },

  // Stage 4: Prepare for Onboarding (3 tasks) — all Draft
  {
    id: 'rec_task_sc_010',
    taskName: 'Watch Setup Video',
    customer: ['rec_cust_sarah_001'],
    type: 'Client',
    stage: 'Prepare for Onboarding',
    status: 'Draft',
    taskOrder: 1,
    assignedTo: null,
    visibleToClient: true,
    dependsOn: 'Send Credentials',
    hasTeamReview: false,
    attachmentType: 'Embed',
    embedUrl: '',
    instructions: 'Watch this short video to learn how to connect and configure your service areas.',
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-10T09:30:00.000Z',
  },
  {
    id: 'rec_task_sc_011',
    taskName: 'Sign In & Reset Password',
    customer: ['rec_cust_sarah_001'],
    type: 'Client',
    stage: 'Prepare for Onboarding',
    status: 'Draft',
    taskOrder: 2,
    assignedTo: null,
    visibleToClient: true,
    dependsOn: 'Send Credentials',
    hasTeamReview: false,
    attachmentType: 'None',
    embedUrl: '',
    instructions: 'Log in to app.rejig.ai using the credentials we sent and reset your password.',
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-10T09:30:00.000Z',
  },
  {
    id: 'rec_task_sc_012',
    taskName: 'Mark Onboarding Call Complete',
    customer: ['rec_cust_sarah_001'],
    type: 'Team',
    stage: 'Prepare for Onboarding',
    status: 'Draft',
    taskOrder: 3,
    assignedTo: 'CSM',
    visibleToClient: false,
    dependsOn: '',
    hasTeamReview: false,
    attachmentType: 'None',
    embedUrl: '',
    instructions: 'Mark complete after the onboarding call has taken place. If no-show or rescheduled, add a comment with the new date.',
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-10T09:30:00.000Z',
  },

  // Stage 5: Post Onboarding Follow Ups (2 tasks) — all Draft
  {
    id: 'rec_task_sc_013',
    taskName: 'Send Zoom Recording',
    customer: ['rec_cust_sarah_001'],
    type: 'Team',
    stage: 'Post Onboarding Follow Ups',
    status: 'Draft',
    taskOrder: 1,
    assignedTo: 'CSM',
    visibleToClient: false,
    dependsOn: '',
    hasTeamReview: false,
    attachmentType: 'None',
    embedUrl: '',
    instructions: 'Upload or send the onboarding call Zoom recording to the customer.',
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-10T09:30:00.000Z',
  },
  {
    id: 'rec_task_sc_014',
    taskName: 'Send Follow-Up Email',
    customer: ['rec_cust_sarah_001'],
    type: 'Team',
    stage: 'Post Onboarding Follow Ups',
    status: 'Draft',
    taskOrder: 2,
    assignedTo: 'CSM',
    visibleToClient: false,
    dependsOn: '',
    hasTeamReview: false,
    attachmentType: 'None',
    embedUrl: '',
    instructions: 'Send summary of what was covered, outstanding items, and next steps.',
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-10T09:30:00.000Z',
  },

  // Stage 6: Review & Grow (3 tasks) — all Draft
  {
    id: 'rec_task_sc_015',
    taskName: 'Provide Onboarding Feedback',
    customer: ['rec_cust_sarah_001'],
    type: 'Client',
    stage: 'Review & Grow',
    status: 'Draft',
    taskOrder: 1,
    assignedTo: null,
    visibleToClient: true,
    dependsOn: '',
    hasTeamReview: false,
    attachmentType: 'Form',
    embedUrl: '',
    instructions: "We'd love your feedback on the onboarding experience.",
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-10T09:30:00.000Z',
  },
  {
    id: 'rec_task_sc_016',
    taskName: 'Schedule Check-In 1',
    customer: ['rec_cust_sarah_001'],
    type: 'Client',
    stage: 'Review & Grow',
    status: 'Draft',
    taskOrder: 2,
    assignedTo: null,
    visibleToClient: true,
    dependsOn: 'Provide Onboarding Feedback',
    hasTeamReview: false,
    attachmentType: 'Embed',
    embedUrl: '',
    instructions: 'Schedule your first check-in call.',
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-10T09:30:00.000Z',
  },
  {
    id: 'rec_task_sc_017',
    taskName: 'Schedule Check-In 2',
    customer: ['rec_cust_sarah_001'],
    type: 'Client',
    stage: 'Review & Grow',
    status: 'Draft',
    taskOrder: 3,
    assignedTo: null,
    visibleToClient: true,
    dependsOn: 'Schedule Check-In 1',
    hasTeamReview: false,
    attachmentType: 'Embed',
    embedUrl: '',
    instructions: 'Schedule your second check-in call.',
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-10T09:30:00.000Z',
  },
];

// ─── Tasks: James Rodriguez (Keyes — 11 tasks) ──────────────────────

const jamesTasks: Task[] = [
  // Stage 1: Getting Started (3 tasks) — all Active
  {
    id: 'rec_task_jr_001',
    taskName: 'Confirm Your Information',
    customer: ['rec_cust_james_002'],
    type: 'Client',
    stage: 'Getting Started',
    status: 'Active',
    taskOrder: 1,
    assignedTo: null,
    visibleToClient: true,
    dependsOn: '',
    hasTeamReview: false,
    attachmentType: 'Form',
    embedUrl: '',
    instructions: 'Review the information we have on file for you. If anything needs updating, let us know via Messages.',
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-21T10:00:00.000Z',
  },
  {
    id: 'rec_task_jr_002',
    taskName: 'Start Your Trial',
    customer: ['rec_cust_james_002'],
    type: 'Client',
    stage: 'Getting Started',
    status: 'Active',
    taskOrder: 2,
    assignedTo: null,
    visibleToClient: true,
    dependsOn: '',
    hasTeamReview: false,
    attachmentType: 'None',
    embedUrl: '',
    instructions: 'Follow the instructions to activate your trial account.',
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-21T10:00:00.000Z',
  },
  {
    id: 'rec_task_jr_003',
    taskName: 'Schedule Your Onboarding Call',
    customer: ['rec_cust_james_002'],
    type: 'Client',
    stage: 'Getting Started',
    status: 'Active',
    taskOrder: 3,
    assignedTo: null,
    visibleToClient: true,
    dependsOn: '',
    hasTeamReview: false,
    attachmentType: 'Embed',
    embedUrl: '',
    instructions: 'Book your onboarding call at a time that works for you.',
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-21T10:00:00.000Z',
  },

  // Stage 2: Prepare for Onboarding (5 tasks) — all Draft
  {
    id: 'rec_task_jr_004',
    taskName: 'Create Customer Account',
    customer: ['rec_cust_james_002'],
    type: 'Team',
    stage: 'Prepare for Onboarding',
    status: 'Draft',
    taskOrder: 1,
    assignedTo: 'Onboarding Ops',
    visibleToClient: false,
    dependsOn: '',
    hasTeamReview: false,
    attachmentType: 'None',
    embedUrl: '',
    instructions: "Create the agent's app.rejig.ai account using their roster email.",
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-21T10:00:00.000Z',
  },
  {
    id: 'rec_task_jr_005',
    taskName: 'Send Credentials',
    customer: ['rec_cust_james_002'],
    type: 'Team',
    stage: 'Prepare for Onboarding',
    status: 'Draft',
    taskOrder: 2,
    assignedTo: 'Onboarding Ops',
    visibleToClient: false,
    dependsOn: 'Create Customer Account',
    hasTeamReview: false,
    attachmentType: 'None',
    embedUrl: '',
    instructions: 'Send login credentials to the agent.',
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-21T10:00:00.000Z',
  },
  {
    id: 'rec_task_jr_006',
    taskName: 'Watch Setup Video',
    customer: ['rec_cust_james_002'],
    type: 'Client',
    stage: 'Prepare for Onboarding',
    status: 'Draft',
    taskOrder: 3,
    assignedTo: null,
    visibleToClient: true,
    dependsOn: 'Send Credentials',
    hasTeamReview: false,
    attachmentType: 'Embed',
    embedUrl: '',
    instructions: 'Watch this short video to learn how to connect and configure your service areas.',
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-21T10:00:00.000Z',
  },
  {
    id: 'rec_task_jr_007',
    taskName: 'Sign In & Reset Password',
    customer: ['rec_cust_james_002'],
    type: 'Client',
    stage: 'Prepare for Onboarding',
    status: 'Draft',
    taskOrder: 4,
    assignedTo: null,
    visibleToClient: true,
    dependsOn: 'Send Credentials',
    hasTeamReview: false,
    attachmentType: 'None',
    embedUrl: '',
    instructions: 'Log in to app.rejig.ai using the credentials we sent and reset your password.',
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-21T10:00:00.000Z',
  },
  {
    id: 'rec_task_jr_008',
    taskName: 'Mark Onboarding Call Complete',
    customer: ['rec_cust_james_002'],
    type: 'Team',
    stage: 'Prepare for Onboarding',
    status: 'Draft',
    taskOrder: 5,
    assignedTo: 'CSM',
    visibleToClient: false,
    dependsOn: '',
    hasTeamReview: false,
    attachmentType: 'None',
    embedUrl: '',
    instructions: 'Mark complete after the onboarding call. Add comments if rescheduled.',
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-21T10:00:00.000Z',
  },

  // Stage 3: Review & Grow (3 tasks) — all Draft
  {
    id: 'rec_task_jr_009',
    taskName: 'Provide Onboarding Feedback',
    customer: ['rec_cust_james_002'],
    type: 'Client',
    stage: 'Review & Grow',
    status: 'Draft',
    taskOrder: 1,
    assignedTo: null,
    visibleToClient: true,
    dependsOn: '',
    hasTeamReview: false,
    attachmentType: 'Form',
    embedUrl: '',
    instructions: "We'd love your feedback on the onboarding experience.",
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-21T10:00:00.000Z',
  },
  {
    id: 'rec_task_jr_010',
    taskName: 'Schedule Check-In 1',
    customer: ['rec_cust_james_002'],
    type: 'Client',
    stage: 'Review & Grow',
    status: 'Draft',
    taskOrder: 2,
    assignedTo: null,
    visibleToClient: true,
    dependsOn: 'Provide Onboarding Feedback',
    hasTeamReview: false,
    attachmentType: 'Embed',
    embedUrl: '',
    instructions: 'Schedule your first check-in call.',
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-21T10:00:00.000Z',
  },
  {
    id: 'rec_task_jr_011',
    taskName: 'Schedule Check-In 2',
    customer: ['rec_cust_james_002'],
    type: 'Client',
    stage: 'Review & Grow',
    status: 'Draft',
    taskOrder: 3,
    assignedTo: null,
    visibleToClient: true,
    dependsOn: 'Schedule Check-In 1',
    hasTeamReview: false,
    attachmentType: 'Embed',
    embedUrl: '',
    instructions: 'Schedule your second check-in call.',
    tags: [],
    notes: '',
    dueDate: '',
    completedAt: '',
    createdAt: '2026-04-21T10:00:00.000Z',
  },
];

// ─── Events ──────────────────────────────────────────────────────────

export const events: Event[] = [
  {
    id: 'rec_evt_001',
    eventId: 1,
    customer: ['rec_cust_sarah_001'],
    eventType: 'Customer Created',
    actor: 'System',
    details: 'Customer record created for Sarah Chen (D2C Standard, Luxury tier).',
    relatedTask: [],
    createdAt: '2026-04-10T09:30:00.000Z',
  },
  {
    id: 'rec_evt_002',
    eventId: 2,
    customer: ['rec_cust_sarah_001'],
    eventType: 'Task Completed',
    actor: 'Customer',
    details: 'Sarah completed the onboarding form.',
    relatedTask: ['rec_task_sc_001'],
    createdAt: '2026-04-12T11:30:00.000Z',
  },
  {
    id: 'rec_evt_003',
    eventId: 3,
    customer: ['rec_cust_sarah_001'],
    eventType: 'Task Completed',
    actor: 'Customer',
    details: 'Sarah uploaded logos and headshots.',
    relatedTask: ['rec_task_sc_002'],
    createdAt: '2026-04-13T16:45:00.000Z',
  },
  {
    id: 'rec_evt_004',
    eventId: 4,
    customer: ['rec_cust_sarah_001'],
    eventType: 'Task Activated',
    actor: 'System',
    details: 'Create Designs activated — dependency "Upload Logos and Headshots" completed.',
    relatedTask: ['rec_task_sc_003'],
    createdAt: '2026-04-13T16:45:01.000Z',
  },
  {
    id: 'rec_evt_005',
    eventId: 5,
    customer: ['rec_cust_sarah_001'],
    eventType: 'Task Completed',
    actor: 'Senior Designer',
    details: 'Brand kit designs reviewed and approved by senior designer.',
    relatedTask: ['rec_task_sc_003'],
    createdAt: '2026-04-17T10:00:00.000Z',
  },
  {
    id: 'rec_evt_006',
    eventId: 6,
    customer: ['rec_cust_sarah_001'],
    eventType: 'Stage Changed',
    actor: 'System',
    details: 'Stage advanced from "Getting Started" to "Review Your Designs".',
    relatedTask: [],
    createdAt: '2026-04-18T14:00:00.000Z',
  },
  {
    id: 'rec_evt_007',
    eventId: 7,
    customer: ['rec_cust_james_002'],
    eventType: 'Customer Created',
    actor: 'System',
    details: 'Customer record created for James Rodriguez (Keyes). Data pre-populated from roster.',
    relatedTask: [],
    createdAt: '2026-04-21T10:00:00.000Z',
  },
];

// ─── All tasks combined ──────────────────────────────────────────────

export const tasks: Task[] = [...sarahTasks, ...jamesTasks];

// Wire up task IDs on customer records
customers[0].tasks = sarahTasks.map((t) => t.id);
customers[0].events = events.filter((e) => e.customer.includes('rec_cust_sarah_001')).map((e) => e.id);
customers[1].tasks = jamesTasks.map((t) => t.id);
customers[1].events = events.filter((e) => e.customer.includes('rec_cust_james_002')).map((e) => e.id);
