/**
 * Phase 1b of the DMG roster integration plan: stand up Illustrated Properties
 * Real Estate (IPRE) as the third B2B brokerage.
 *
 * Per the IPRE workflow_key memory (Option A locked 2026-05-19):
 *   - New channel `IPRE` (B2B).
 *   - New brokerage row with landing_page_slug='ipre', default_workflow_key='B2B-IPRE'.
 *   - Duplicate the B2B-Keyes workflow_templates rows to B2B-IPRE so the
 *     two flows can drift independently going forward.
 *
 * Template-level dependencies live in `workflow_templates.depends_on`
 * (comma-separated task-title text), NOT in task_dependencies. The
 * task_dependencies junction table is for per-customer RUNTIME tasks
 * generated by Auto 1 — do not touch it here.
 *
 * All work runs inside one db.transaction; any throw rolls everything back.
 * Idempotent:
 *   - Channel insert uses ON CONFLICT (code) DO NOTHING.
 *   - Brokerage insert uses ON CONFLICT (landing_page_slug) DO NOTHING.
 *   - Template duplication is sentinel-guarded: if any B2B-IPRE rows already
 *     exist, the duplication step is skipped.
 *
 * NOTE: Several values are TBD placeholders; fill them in before running.
 *   - IPRE support contact name / email / phone
 *   - IPRE master logo URL
 *   - IPRE default Calendly URL
 *
 * Usage: npx tsx scripts/seed-ipre-launch.ts
 */
import dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

// Filled 2026-05-26 from product owner. Support name/phone not provided → null.
const IPRE_SUPPORT_CONTACT_NAME: string | null = null;
const IPRE_SUPPORT_CONTACT_EMAIL: string | null = 'support@rejig.ai';
const IPRE_SUPPORT_CONTACT_PHONE: string | null = null;
const IPRE_MASTER_LOGO_URL: string | null =
  'https://z0rxtnzxdkzzt5wn.public.blob.vercel-storage.com/brokerage-logos/ipre-jade.svg';
const IPRE_DEFAULT_CALENDLY_URL: string | null =
  'https://meetings-na2.hubspot.com/mario-giron/onboarding-meeting-link';

const SOURCE_WORKFLOW_KEY = 'B2B-Keyes';
const TARGET_WORKFLOW_KEY = 'B2B-IPRE';

async function main() {
  const { db } = await import('../src/db');
  const { channels } = await import('../src/db/schema/channels');
  const { brokerages } = await import('../src/db/schema/brokerages');
  const { workflowTemplates } = await import('../src/db/schema/workflowTemplates');
  const { eq, asc, sql } = await import('drizzle-orm');

  type NewChannel = typeof channels.$inferInsert;
  type NewBrokerage = typeof brokerages.$inferInsert;
  type NewWorkflowTemplate = typeof workflowTemplates.$inferInsert;

  await db.transaction(async (tx) => {
    // -------------------------------------------------------------------
    // Step 1. Insert IPRE channel.
    // -------------------------------------------------------------------
    console.log('Step 1: Inserting IPRE channel...');
    const channelRow: NewChannel = {
      code: 'IPRE',
      displayName: 'Illustrated Properties Real Estate',
      customerType: 'B2B',
      active: true,
    };
    const channelResult = await tx
      .insert(channels)
      .values(channelRow)
      .onConflictDoNothing({ target: channels.code })
      .returning({ id: channels.id, code: channels.code });

    if (channelResult.length === 0) {
      console.log('  Channel IPRE already exists — skipped.');
    } else {
      console.log(`  Inserted channel IPRE (id=${channelResult[0].id}).`);
    }

    // -------------------------------------------------------------------
    // Step 2. Insert IPRE brokerage.
    // -------------------------------------------------------------------
    console.log('\nStep 2: Inserting IPRE brokerage...');
    const brokerageRow: NewBrokerage = {
      name: 'Illustrated Properties Real Estate',
      landingPageSlug: 'ipre',
      defaultWorkflowKey: TARGET_WORKFLOW_KEY,
      defaultCalendlyUrl: IPRE_DEFAULT_CALENDLY_URL,
      hubspotCompanyId: null,
      active: true,
      includesVoice: false,
      includesAvatar: false,
      masterLogoUrl: IPRE_MASTER_LOGO_URL,
      sourceType: 'dmg',
      sourceConfig: { credEnvPrefix: 'DMG_IPRE' },
      verificationMode: 'soft',
      supportContactName: IPRE_SUPPORT_CONTACT_NAME,
      supportContactEmail: IPRE_SUPPORT_CONTACT_EMAIL,
      supportContactPhone: IPRE_SUPPORT_CONTACT_PHONE,
    };
    const brokerageResult = await tx
      .insert(brokerages)
      .values(brokerageRow)
      .onConflictDoNothing({ target: brokerages.landingPageSlug })
      .returning({ id: brokerages.id, slug: brokerages.landingPageSlug });

    if (brokerageResult.length === 0) {
      console.log('  Brokerage with slug=ipre already exists — skipped.');
    } else {
      console.log(`  Inserted brokerage IPRE (id=${brokerageResult[0].id}, slug=${brokerageResult[0].slug}).`);
    }

    // -------------------------------------------------------------------
    // Step 3. Duplicate B2B-Keyes workflow_templates rows to B2B-IPRE.
    //
    // Sentinel guard: if B2B-IPRE rows already exist, skip duplication.
    // (Don't UPSERT — drift is acceptable once IPRE templates exist.)
    // -------------------------------------------------------------------
    console.log(`\nStep 3: Duplicating templates ${SOURCE_WORKFLOW_KEY} → ${TARGET_WORKFLOW_KEY}...`);

    const existing = await tx
      .select({ count: sql<number>`count(*)::int` })
      .from(workflowTemplates)
      .where(eq(workflowTemplates.workflowKey, TARGET_WORKFLOW_KEY));
    const existingCount = existing[0]?.count ?? 0;

    if (existingCount > 0) {
      console.log(`  ${existingCount} ${TARGET_WORKFLOW_KEY} row(s) already exist — skipping duplication.`);
      return;
    }

    const sourceRows = await tx
      .select()
      .from(workflowTemplates)
      .where(eq(workflowTemplates.workflowKey, SOURCE_WORKFLOW_KEY))
      .orderBy(asc(workflowTemplates.stageOrder), asc(workflowTemplates.taskOrder));

    console.log(`  Read ${sourceRows.length} ${SOURCE_WORKFLOW_KEY} template row(s).`);

    if (sourceRows.length === 0) {
      throw new Error(
        `No ${SOURCE_WORKFLOW_KEY} workflow_templates rows found. Refusing to insert an empty IPRE template set.`,
      );
    }

    // Spread each source row, drop id (regenerated), flip workflow_key.
    // `depends_on` text is portable — task titles are shared between Keyes
    // and IPRE template sets.
    const newRows: NewWorkflowTemplate[] = sourceRows.map((src) => {
      const { id: _id, ...rest } = src;
      return {
        ...rest,
        workflowKey: TARGET_WORKFLOW_KEY,
      };
    });

    const inserted = await tx
      .insert(workflowTemplates)
      .values(newRows)
      .returning({
        id: workflowTemplates.id,
        workflowKey: workflowTemplates.workflowKey,
        stage: workflowTemplates.stage,
        taskTitle: workflowTemplates.taskTitle,
      });

    console.log(`  Inserted ${inserted.length} ${TARGET_WORKFLOW_KEY} template row(s).`);
    for (const r of inserted) {
      console.log(`    - [${r.stage}] ${r.taskTitle}`);
    }
  });

  console.log('\nDone. IPRE launch seed complete.');
}

main().then(() => process.exit(0)).catch((e) => { console.error(e); process.exit(1); });
