/**
 * One-shot, idempotent HubSpot property bootstrap.
 *
 *   npx tsx scripts/setup-hubspot-properties.ts          # dry-run (default)
 *   npx tsx scripts/setup-hubspot-properties.ts --apply  # actually create
 *
 * Reads existing properties via `GET /crm/v3/properties/{objectType}`; for
 * each property in the spec table below, prints one of:
 *
 *   ✓ exists      — already in HubSpot, no-op
 *   + created     — newly created (apply mode)
 *   ~ would create — would be created (dry-run)
 *   ✗ failed      — API rejected the create call (logged + counted)
 *
 * Designed to be safe to re-run any number of times — never modifies an
 * existing property (no PATCH calls), only creates missing ones. If a
 * property exists with a different type/options, leave it alone; sort out
 * mismatches in the HubSpot UI manually.
 *
 * Property spec sources:
 *   - docs/integrations/hubspot-integration-phase-0b-setup.md (originals)
 *   - docs/plans/post-launch-migration-pass-2-7.md           (BI cron set)
 *   - src/lib/bi/types.ts                                     (enum vocab)
 *
 * Auth: uses HUBSPOT_STATIC_TOKEN from .env.local (same as runtime code).
 * Required scopes (already on the LP app): crm.schemas.contacts.write,
 *   crm.schemas.deals.write, crm.schemas.companies.write,
 *   crm.schemas.custom.write (covers tickets).
 */
import * as dotenv from 'dotenv';
import { Client } from '@hubspot/api-client';
import {
  PropertyCreateTypeEnum,
  PropertyCreateFieldTypeEnum,
} from '@hubspot/api-client/lib/codegen/crm/properties/models/PropertyCreate';

dotenv.config({ path: '.env.local' });

import {
  PROFILE_VALUES,
  TRAJECTORY_VALUES,
  OUTCOME_VALUES,
  ATTENTION_REASON_VALUES,
  PAYMENT_MODE_VALUES,
  ACTION_URGENCY_VALUES,
  BROKERAGE_CHANNEL_VALUES,
} from './setup-hubspot-properties.enums';

const APPLY = process.argv.includes('--apply');

type ObjectType = 'contacts' | 'tickets' | 'deals' | 'companies';

type EnumOption = { label: string; value: string };

type PropSpec = {
  name: string;
  label: string;
  type: 'string' | 'number' | 'date' | 'datetime' | 'enumeration';
  fieldType: 'text' | 'textarea' | 'number' | 'date' | 'select';
  description: string;
  options?: EnumOption[];
};

// HubSpot default group names — same as what the UI uses.
const DEFAULT_GROUP: Record<ObjectType, string> = {
  contacts: 'contactinformation',
  tickets: 'ticketinformation',
  deals: 'dealinformation',
  companies: 'companyinformation',
};

const opts = (vals: readonly string[]): EnumOption[] =>
  vals.map((v) => ({ label: v, value: v }));

// ─────────────────────────────────────────────────────────────────────
// SPEC: every LaunchPad-related property across the 4 HubSpot objects.
// Idempotent — pre-existing entries get `✓ exists`.
// ─────────────────────────────────────────────────────────────────────
const SPEC: Record<ObjectType, PropSpec[]> = {
  contacts: [
    {
      name: 'launchpad_customer_id',
      label: 'LaunchPad Customer ID',
      type: 'string',
      fieldType: 'text',
      description: 'UUID generated by LaunchPad. Cross-system anchor.',
    },
    {
      name: 'stripe_customer_id',
      label: 'Stripe Customer ID',
      type: 'string',
      fieldType: 'text',
      description: 'Stripe customer (cus_XXX). One per customer.',
    },
    {
      name: 'rejig_user_id',
      label: 'Rejig User ID',
      type: 'string',
      fieldType: 'text',
      description: 'Rejig app user account ID (Mongo _id), populated after account creation.',
    },
    {
      name: 'rejig_brokerage_channel',
      label: 'Rejig Brokerage Channel',
      type: 'enumeration',
      fieldType: 'select',
      description: 'Customer type + brokerage in one field, for kanban filtering + reports.',
      options: opts(BROKERAGE_CHANNEL_VALUES),
    },
    {
      name: 'rejig_payment_mode',
      label: 'Rejig Payment Mode',
      type: 'enumeration',
      fieldType: 'select',
      description: 'How this customer pays: pre-paid (D2C), setup-intent-at-intake (Keyes trial), invoice (B&W), none.',
      options: opts(PAYMENT_MODE_VALUES),
    },
    {
      name: 'rejig_billing_relationship',
      label: 'Rejig Billing Relationship',
      type: 'enumeration',
      fieldType: 'select',
      description: 'paying = billed customer. comped = real user, billing waived (sponsor exec, brokerage comp). internal_demo = Rejig-internal account; BI cron skips entirely.',
      options: opts(['paying', 'comped', 'internal_demo']),
    },
    {
      name: 'onboarding_no_show_count',
      label: 'Onboarding No-Show Count',
      type: 'number',
      fieldType: 'number',
      description: 'HubSpot Workflow B increments on no-show; Workflow A resets to 0 on Completed.',
    },
    {
      name: 'rejig_engagement_profile',
      label: 'Rejig Engagement Profile',
      type: 'enumeration',
      fieldType: 'select',
      description: 'BI Layer 1 classification (17 buckets). Refreshed weekly by /api/cron/bi.',
      options: opts(PROFILE_VALUES),
    },
    {
      name: 'rejig_predicted_outcome',
      label: 'Rejig Predicted Outcome',
      type: 'enumeration',
      fieldType: 'select',
      description: 'BI Layer 3 outcome prediction (renew / churn / unknown).',
      options: opts(OUTCOME_VALUES),
    },
    {
      name: 'rejig_outcome_reasoning',
      label: 'Rejig Outcome Reasoning',
      type: 'string',
      fieldType: 'textarea',
      description: 'Top-2 predicates the BI cron fired for the predicted outcome, humanized (e.g. "tenure 92d (≥ 30d) · never logged in"). Rendered as microcopy on the Engagement Card.',
    },
    {
      name: 'rejig_last_login',
      label: 'Rejig Last Login',
      type: 'datetime',
      fieldType: 'date',
      description: 'Customer last login to Rejig app (UTC). Mirrored from Rejig API.',
    },
    {
      name: 'rejig_days_since_last_post',
      label: 'Rejig Days Since Last Post',
      type: 'number',
      fieldType: 'number',
      description: 'Days since customer published their last post (any type). Mirrored from Rejig API.',
    },
    {
      name: 'rejig_days_until_expiry',
      label: 'Rejig Days Until Expiry',
      type: 'number',
      fieldType: 'number',
      description: 'Days until Stripe plan expires (renewal anchor). Mirrored from Rejig API.',
    },
    {
      name: 'rejig_trajectory_confidence',
      label: 'Rejig Trajectory Confidence',
      type: 'enumeration',
      fieldType: 'select',
      description: 'Trajectory derivation confidence (low/medium/high). Surfaced next to "Predicted" on the HS Engagement Card.',
      options: opts(['low', 'medium', 'high']),
    },
    {
      name: 'rejig_plan_name',
      label: 'Rejig Plan Name',
      type: 'string',
      fieldType: 'text',
      description: 'customers.selectedPlanName mirror — surfaced on HS Engagement Card alongside expiry.',
    },
    {
      name: 'rejig_posting_trajectory',
      label: 'Rejig Posting Trajectory',
      type: 'enumeration',
      fieldType: 'select',
      description: 'BI Layer 2 trajectory pattern over the last 6 weekly snapshots.',
      options: opts(TRAJECTORY_VALUES),
    },
    {
      name: 'rejig_listing_count',
      label: 'Rejig Listing Count',
      type: 'number',
      fieldType: 'number',
      description: 'Active listings on the Rejig account. Mirrored from Rejig API by BI cron.',
    },
    {
      name: 'rejig_total_posts',
      label: 'Rejig Total Posts',
      type: 'number',
      fieldType: 'number',
      description: 'Cumulative posts published on Rejig (all types). Mirrored from Rejig API by BI cron.',
    },
    {
      name: 'rejig_video_posts',
      label: 'Rejig Video Posts',
      type: 'number',
      fieldType: 'number',
      description: 'Cumulative video posts published. Mirrored from Rejig API by BI cron.',
    },
    {
      name: 'rejig_image_posts',
      label: 'Rejig Image Posts',
      type: 'number',
      fieldType: 'number',
      description: 'Cumulative image posts published. Mirrored from Rejig API by BI cron.',
    },
    {
      name: 'rejig_posts_last_7d',
      label: 'Rejig Posts Last 7d',
      type: 'number',
      fieldType: 'number',
      description: 'Posts published since the previous weekly snapshot. Null if fewer than 2 snapshots ("too early").',
    },
    {
      name: 'rejig_signals_observed_at',
      label: 'Rejig Signals Observed At',
      type: 'datetime',
      fieldType: 'date',
      description: 'observed_at of the most recent Rejig API snapshot for this customer. Card freshness indicator.',
    },
  ],
  tickets: [
    {
      name: 'rejig_attention_reason',
      label: 'Rejig Attention Reason',
      type: 'enumeration',
      fieldType: 'select',
      description: 'The "why" behind Watch/At-Risk/Critical severity (10 locked values).',
      options: opts(ATTENTION_REASON_VALUES),
    },
    {
      name: 'rejig_attention_set_at',
      label: 'Rejig Attention Set At',
      type: 'datetime',
      fieldType: 'date',
      description: 'When the current attention state started.',
    },
    {
      name: 'rejig_recommended_action',
      label: 'Rejig Recommended Action',
      type: 'string',
      fieldType: 'textarea',
      description: 'CSM-facing summary of the recommended action template that fired (A1–A15).',
    },
    {
      name: 'rejig_recommended_action_set_at',
      label: 'Rejig Recommended Action Set At',
      type: 'datetime',
      fieldType: 'date',
      description: 'When the BI cron last set rejig_recommended_action.',
    },
    {
      name: 'rejig_recommended_action_urgency',
      label: 'Rejig Recommended Action Urgency',
      type: 'enumeration',
      fieldType: 'select',
      description: 'today | this_week | monitor — drives CSM queue ordering.',
      options: opts(ACTION_URGENCY_VALUES),
    },
  ],
  deals: [
    {
      name: 'launchpad_customer_id',
      label: 'LaunchPad Customer ID',
      type: 'string',
      fieldType: 'text',
      description: 'LaunchPad writes the LP customer UUID after closedwon → ticket creation.',
    },
  ],
  companies: [
    {
      name: 'launchpad_brokerage_id',
      label: 'LaunchPad Brokerage ID',
      type: 'string',
      fieldType: 'text',
      description: 'LaunchPad brokerage UUID — cross-system anchor for B2B brokerage Companies.',
    },
  ],
};

function getClient(): Client {
  const token = process.env.HUBSPOT_STATIC_TOKEN;
  if (!token) {
    console.error('✗ HUBSPOT_STATIC_TOKEN is not set in .env.local');
    process.exit(1);
  }
  return new Client({ accessToken: token });
}

async function listExistingNames(
  hs: Client,
  objectType: ObjectType,
): Promise<Set<string>> {
  const result = await hs.crm.properties.coreApi.getAll(objectType);
  return new Set(result.results.map((p) => p.name));
}

async function processObject(hs: Client, objectType: ObjectType): Promise<{
  existing: number;
  created: number;
  wouldCreate: number;
  failed: number;
}> {
  const specs = SPEC[objectType];
  const tally = { existing: 0, created: 0, wouldCreate: 0, failed: 0 };

  console.log(`\n━━ ${objectType.toUpperCase()} (${specs.length} property/-ies) ━━`);

  let existing: Set<string>;
  try {
    existing = await listExistingNames(hs, objectType);
  } catch (err) {
    console.error(`  ✗ Failed to list ${objectType} properties:`, err instanceof Error ? err.message : err);
    return tally;
  }

  for (const spec of specs) {
    if (existing.has(spec.name)) {
      console.log(`  ✓ exists       ${spec.name}`);
      tally.existing++;
      continue;
    }

    if (!APPLY) {
      console.log(`  ~ would create ${spec.name}  (${spec.type}${spec.options ? `, ${spec.options.length} options` : ''})`);
      tally.wouldCreate++;
      continue;
    }

    try {
      await hs.crm.properties.coreApi.create(objectType, {
        name: spec.name,
        label: spec.label,
        type: spec.type as unknown as PropertyCreateTypeEnum,
        fieldType: spec.fieldType as unknown as PropertyCreateFieldTypeEnum,
        groupName: DEFAULT_GROUP[objectType],
        description: spec.description,
        ...(spec.options
          ? {
              options: spec.options.map((o, i) => ({
                label: o.label,
                value: o.value,
                displayOrder: i,
                hidden: false,
              })),
            }
          : {}),
      });
      console.log(`  + created      ${spec.name}`);
      tally.created++;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.log(`  ✗ failed       ${spec.name}  — ${msg}`);
      tally.failed++;
    }
  }

  return tally;
}

async function main(): Promise<void> {
  console.log(`HubSpot property bootstrap — mode: ${APPLY ? 'APPLY (will create missing)' : 'DRY-RUN (no writes)'}`);
  const hs = getClient();

  const grandTally = { existing: 0, created: 0, wouldCreate: 0, failed: 0 };

  for (const objectType of ['contacts', 'tickets', 'deals', 'companies'] as const) {
    const tally = await processObject(hs, objectType);
    grandTally.existing += tally.existing;
    grandTally.created += tally.created;
    grandTally.wouldCreate += tally.wouldCreate;
    grandTally.failed += tally.failed;
  }

  console.log(`\n━━ SUMMARY ━━`);
  console.log(`  existing:     ${grandTally.existing}`);
  if (APPLY) {
    console.log(`  created:      ${grandTally.created}`);
  } else {
    console.log(`  would create: ${grandTally.wouldCreate}`);
  }
  if (grandTally.failed > 0) {
    console.log(`  FAILED:       ${grandTally.failed}`);
    process.exit(1);
  }

  if (!APPLY && grandTally.wouldCreate > 0) {
    console.log(`\nRe-run with --apply to create the ${grandTally.wouldCreate} missing property/-ies.`);
  }
}

main().catch((err) => {
  console.error('Unhandled error:', err);
  process.exit(1);
});
